language: node_js
node_js: 6.9.5

branches:
    only:
        - master
addons:
    hosts:
        - localhost
before_script:
    - 'npm install -g grunt-cli'
script:
    - 'grunt coverage'
after_success:
    - 'node ./soajs.cd.js'
