swagger: "2.0"
info:
  version: "1.0.0"
  title: demopoc
host: localhost
basePath: /demopoc
schemes:
  - http
paths:
    /readData:
        get:
            summary: Read Data from Database
parameters:

definitions: