swagger: '2.0'
info:
    version: 1.0.0
    title: demopoc
host: localhost
basePath: /demopoc
schemes:
    - http
paths:
    /getStatic:
        get:
            tags:
                - general
            summary: 'Return a static string'
            operationId: Returnastaticstring
    /readData:
        get:
            tags:
                - general
            summary: 'Read Data from Database'
            operationId: ReadDatafromDatabase